### ISSUE TITLE
Nagrand error

### ISSUE THREAD

**Issue by 2ndHouse** [phanx-wow/MountMe#10]
Just an error I seen in Nagrand, it was caused by having the zone specific mount. I changed Nagrand buildings and the error went away

2x MountMe\Addon.lua:207: attempt to call upvalue 'HasDraenorZoneAbility' (a nil value)
MountMe\Addon.lua:207: in function <MountMe\Addon.lua:197>
MountMe\Addon.lua:264: in function <MountMe\Addon.lua:260>

Locals:
name = "Frostwolf War Wolf"
_ = ""
_ = 524154
_ = 1500
_ = 0
_ = 0
id = 164222
(_temporary) = nil
(_temporary) = "attempt to call upvalue 'HasDraenorZoneAbility' (a nil value)"
IsMoving = <function> defined @MountMe\Addon.lua:48
GetItemCount = <function> defined =[C]:-1
GetSpellInfo = <function> defined =[C]:-1
GARRISON_ABILITY = "Garrison Ability"
HasDraenorZoneAbility = nil
SecureCmdOptionParse = <function> defined =[C]:-1
GARRISON_MOUNT_CONDITION = "[outdoors,nomounted,novehicleui,nomod:ctrl]"
ns = <table> {
 CanFly = <function> defined @MountMe\API_CanFly.lua:27
}
HasRidingSkill = <function> defined @MountMe\Addon.lua:57
MOUNT_CONDITION = "[outdoors,nocombat,nomounted,novehicleui]"
MOD_TRAVEL_FORM = "ctrl"
IsSubmerged = <function> defined =[C]:-1
GetMountInfoByID = <function> defined @AnyFavoriteMount\Addon.lua:101
VASHJIR_SEAHORSE = 373
SUMMON = "/run C_MountJournal.SummonByID(%d)"
SUBDUED_SEAHORSE = 420
SEA_LEGS = "Sea Legs"
SEA_TURTLE = 0
AQBUGS = <table> {
 1 = 117
 2 = 120
 3 = 118
 4 = 119
}
hasBugs = <table> {
}

**Comment by Phanx** [comment]
It looks like the Draenor zone ability functions have been removed in 
favor of a more generic zone ability API.

I don't currently have an active subscription so I can't test this 
myself, but can you run this command while in Nagrand with the mount 
building (I forget what it's called) and let me know what it says:

     /run local i,g = GetZoneAbilitySpellInfo() local s=GetSpellInfo(i) 
print(i,g,s)

**Comment by Ivaria** [comment]
Hi Phanx,

> /run local i,g = GetZoneAbilitySpellInfo() local s=GetSpellInfo(i) print(i,g,s)
161691 2 Garrison Ability

Thanks!

**Comment by armordecai** [comment]
Fixed
