### ISSUE TITLE
update for bfa

### ISSUE THREAD

**Issue by wowblitz** [phanx-wow/MountMe#13]
Hello,
Looking forward to a update to this addon for bfa.

Researched some info in a attempt to fix it but I'm not good at figuring this stuff out but it looks like the mapID function has been replaced and mapid numbers also changed.

https://wow.curseforge.com/projects/litemount/pages/bfa-area-to-map-number-translation
https://wow.gamepedia.com/Talk:API_GetCurrentMapAreaID

**Comment by kroyer1996** [comment]
Hey i have an issue that does i cant mount/dismount by only adding a keybind in "dismount" since the new beta update, can anyone help me out here?

**Comment by lloydbates** [comment]
Open Addon.lua, find the definition for the vashjirMaps table and update its content
```lua
local vashjirMaps = {
    [204] = true, -- Abyssal Depths
    [201] = true, -- Kelp'thar Forest
    [205] = true, -- Shimmering Expanse
    [203] = true, -- Vashj'ir
}
```

A few lines below this one, mapID will be assigned, change it to look like this
```lua
local mapID = C_Map.GetBestMapForUnit("player")
```

**Comment by wowblitz** [comment]
Thanks, that fixed it for me.

**Comment by Phanx** [comment]
Fixed, thanks.
