### ISSUE TITLE
Low level characters may have a mount

### ISSUE THREAD

**Issue by brknsoul** [phanx-wow/MountMe#3]
6.1 introduces the Chauffeured Chopper mountable by low level characters (<20).

This mount shouldn't be selected once a character has Journeyman Riding (level 40) because the Chauffeured Chopper's speed remains at 160% (ie: It doesn't scale with Riding Training).

**Comment by Phanx** [comment]
I don't actually have this mount, so someone else should grab the latest file off GitHub and verify that it's working as intended.

**Comment by frumpymoons** [comment]
Two lines need to be changed for it to work.

line 187
```lua
local CHAFFEUR = UnitFactionGroup("player") == "Horde" and 679 or 678

-- swap the ids 
local CHAFFEUR = UnitFactionGroup("player") == "Horde" and 678 or 679
```
line 212
```lua
if not not SecureCmdOptionParse(MOUNT_CONDITION..",nomod:"..MOD_TRAVEL_FORM) then

-- not, not not. only not.
if not SecureCmdOptionParse(MOUNT_CONDITION..",nomod:"..MOD_TRAVEL_FORM) then
```

**Comment by frumpymoons** [comment]
This doesn't work with the latest github version.
I think it is not possible with the /cast command.

**Comment by armordecai** [comment]
Fixed
