### ISSUE TITLE
Alt modifier to force ground mount

### ISSUE THREAD

**Issue by 2ndHouse** [phanx-wow/MountMe#8]
Just wondering if this is something you might implement? 7.0 update seems to be working fine so far btw. Like how simple this is compared to similar addons, it just works without having to configure anything.

**Comment by Phanx** [comment]
What would be the use-case for this? Why would you want to use a ground mount in an area where you can fly?

**Comment by 2ndHouse** [comment]
Coming from other mount addons that had this option. Now that flying mounts can act as ground mounts, there are times when you want to use a ground mount instead of a flying mount in non-flying zones. Sometimes you don't want a giant flying mount blocking others views if it's not needed.

Unless MountMe always automatically summons favorited ground mounts over favorited flying mounts in non-flying areas? That would work too, just give the user less control than a modifier.

**Comment by Phanx** [comment]
MountMe defers to the default UI's logic as to what's included in the 
pool for summoning a random mount. I don't remember offhand whether that 
summons flying mounts in non-flying areas; if it does, you can use my 
other addon AnyFavoriteMount, which, in addition to its nominal purpose 
of letting you favorite any mount even if the default UI normally 
wouldn't let you favorite it, does replace the "summon random" logic 
entirely as a side effect.

When updating both addons for the patch I did realize there's a bit of 
duplication between the two addons, and may eventually fold AFM's 
functionality into MountMe, but for now both work just fine together.

**Comment by 2ndHouse** [comment]
Yeah, both Squire3 and GoGoMount let you force cast ground mounts with a modifier, and I always assumed it was because the default UI does not always handle it properly. I know it can especially act wonky in some outdoor instances/raids.

If I ever need to favorite those troublesome mounts then I will give AnyFavoriteMount a try. Hope you do eventually decide to merge the two. Anyway, thanks for the replies. Go ahead and close this if it helps.

**Comment by Phanx** [comment]
Let me know if you encounter a specific situation where one or both 
addons seem to be summoning an inappropriate mount.

On a side note, underwater (turtles and seahorse) and zone-specific 
(AQ40 bugs and Vashj'ir quest seahorse) mounts will be used as 
appropriate without needing to mark them as favorites.
